#!/bin/bash

# Input, Output, Error redirections
# -----------------------------------------------------------------

# This shows the stderr "No such file..."
ls bla.sh

# This redirects stderr to /dev/null
ls bla.sh 2> /dev/null

# This redirects both stderr and stdout to /dev/null
ls bla.sh &> /dev/null

# The < notation redirects command input from a file
filename="temp.txt"

if [ ! -f $filename ];
then
	echo "File does not exist. Creating it..."
	touch temp.txt
	ls -l temp.txt
else
	echo "File exists"
fi

echo "This text was generated by the script" > temp.txt

cat < temp.txt

rm temp.txt
echo "temp.txt delete"
