#!/bin/bash

declare -r log_dir_path="$HOME/dropbox/log"
declare -r log_filename="rclonesync.txt"
declare -r log_events_filename="rclonesync-events.txt"

function logger {
  if [ -d "$log_dir_path" ]
  then
    printf "%-22s%-8s%s\n" "$(date +"%d-%m-%Y %T")" "$1" "$2" >> "$log_dir_path/$log_events_filename"
  else
    printf "%-22s%-8s%s\n" "$(date +"%d-%m-%Y %T")" "ERROR" "log_dir_path not found! Aborting..."
    exit 1
  fi
}

if [ ! -e "$log_dir_path/$log_filename" ]
then
  logger "ERROR" "rclonesync log file not found! Aborting..."
  exit 1
fi

if [ ! $(tail -n 2 "$log_dir_path/$log_filename" 2> /dev/null | grep "first-sync" | wc -l) -eq 0 ]
then
  logger "EVENT" "rclonesync critical error detected! Initiating first sync..."

  rclonesync --first-sync dropbox:/cctv-usb ~/dropbox &> /dev/null
  if [ $? -eq 0 ]
  then
    logger "EVENT" "First sync completed successfully. Done."
    exit 0
  else
    logger "ERROR" "First sync failed! Aborting..."
    exit 1
  fi
fi